### ISSUE TITLE
FC

### ISSUE THREAD

**Issue by EMK2000** [smartjinyu/SaveNoTPic#1]
不知為甚麼，用 Now on Tap 截圖後，分享，選擇 SaveNoTPic，然後就 FC 了。已經有給權限。

問題是，之前一向用也沒有問題，就今日才發現 FC…

**Comment by EMK2000** [comment]
即使清除 data，或者卸載重新安裝，仍然 FC。

**Comment by EMK2000** [comment]
應該不會因為 Google App 的更新吧…

**Comment by smartjinyu** [comment]
可以复现，我晚上看一下，谢谢反馈

**Comment by smartjinyu** [comment]
确认是Google App更新后Uri格式变化导致的，v1.2更新已解决该问题，感谢反馈
